name: LanguagePack
version: 0.1.0003
description: Custom default item names
author: meiskam

main: org.shininet.bukkit.languagepack.LanguagePack
database: false
depend: [ProtocolLib]

commands:
  LanguagePack:
    description: general LanguagePack command

permissions:
  languagepack.*:
    description: Gives all LanguagePack permissions
    children:
      languagepack.update: true
      languagepack.config.*: true
languagepack.config.*:
    description: Allows user to edit, save, or reload configs
    children:
      languagepack.config.get: true
      languagepack.config.set: true
  languagepack.config.get:
    description: Allows user to get configs
    default: op
  languagepack.config.set:
    description: Allows user to set or reload configs
    default: op
  languagepack.update:
    description: Allows user to update the plugin and view update notices
    default: op