name: ItemRenamer
version: 1.0.0010
description: Custom default item names
author: meiskam

main: org.shininet.bukkit.itemrenamer.ItemRenamer
database: false
depend: [ProtocolLib]

commands:
  ItemRenamer:
    description: general ItemRenamer command

permissions:
  itemrenamer.*:
    description: Gives all ItemRenamer permissions
    children:
      itemrenamer.update: true
      itemrenamer.config.*: true
  itemrenamer.config.*:
    description: Allows user to edit, save, or reload configs
    children:
      itemrenamer.config.get: true
      itemrenamer.config.set: true
  itemrenamer.config.get:
    description: Allows user to get configs
    default: op
  itemrenamer.config.set:
    description: Allows user to set or reload configs
    default: op
  itemrenamer.update:
    description: Allows user to update the plugin and view update notices
    default: op